### ISSUE TITLE
Fix CoC CA translation

### ISSUE THREAD

**Issue by Pardiez** [VLCTechHub/VLCTechFest2019#24]
_data/coc.yaml
- [x] Remove spanish repeated sentence ("Si estás sufriendo algún...") https://github.com/VLCTechHub/VLCTechFest2019/blob/6df7564d558e6ea1f0f7f6ebc2ea578dc60ad5fe/_data/coc.yaml#L43
- [x] Translate to CA and add missing sentence ("Conference staff will be happy...") https://github.com/VLCTechHub/VLCTechFest2019/blob/6df7564d558e6ea1f0f7f6ebc2ea578dc60ad5fe/_data/coc.yaml#L46

**Comment by esebastian** [comment]
I've also took the opportunity to update a few other parts.
